[package]
name = "floris/rfdf"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Sift = "csqrl/sift@0.0.11"
Squash = "data-oriented-house/squash@5.0.0"
Iris = "linuskat/iris-implot@1.0.4"
Janitor = "howmanysmall/janitor@^1.17.0"
RemotePacketSizeCounter = "pysephwasntavailable/remotepacketsizecounter@2.4.1"
LemonSignal = "data-oriented-house/lemonsignal@1.11.0"
DeltaCompress = "nezuo/delta-compress@0.1.3"